//Constants for getting type references
export const FEED_PAGE = 'FeedPage';
export const COMMUNITY_PAGE = 'CommunityPage';
export const FRIENDS_PAGE = 'FriendsPage';
export const CHECKIN_PAGE = 'CheckinPage';
export const SETTINGS_PAGE = 'SettingsPage';
export const FRIENDS_SHARING_PAGE = 'FriendsSharingPage';
export const FRIENDS_VIEW_LOG_PAGE = 'FriendsViewLogPage';
export const COMMUNITY_CHOOSER_PAGE = 'CommunityChooserPage';